### ISSUE TITLE
TODOS Aufgabe 6

### ISSUE THREAD

**Issue by Mcrtin** [frndotmsn/SE2Laborphase2#1]
- [x] #6
- [x] Implementation in AusleihWerkzeug #21
- [x] #4
- [x] #5
- [x] Implementation in StartUpMediathek #21
- [x] #13
- [x] Implementation von VormerkServiceImpl
- [x] #2
- [x] #8
- [x] #3

**Comment by frndotmsn** [comment]
Wir hatten uns darauf geeinigt, AusleiheMedienauflisterWerkzeug nicht zu testen
