### ISSUE TITLE
deprecated method Vormerkkarte#istVormerkenMoeglich

### ISSUE THREAD

**Issue by Mcrtin** [frndotmsn/SE2Laborphase2#22]
anstatt deprecated kann die methode public gelassen werden oder es kann maximaleAnzahlVormerkendeErreicht genutzt werden (indem die Visibility erweitert wird (Tests nicht vergessen)) und ggf. zu istVormerkenMoeglich umbennant werden.

**Comment by frndotmsn** [comment]
Da sie nun nirgends mehr verwendet werden sollte, kann man überprüfen, ob und wo sie noch benutzt wird, alles auf die neue Version updaten und dann Vormerkkarte#istVormerkenMoeglich löschen

**Comment by Mcrtin** [comment]
Wer soll/möchte das machen?

**Comment by YonasUHH** [comment]
kann ich machen
