### ISSUE TITLE
Localer Pfad in .classpath

### ISSUE THREAD

**Issue by Mcrtin** [frndotmsn/SE2Laborphase2#55]
https://github.com/frndotmsn/SE2Laborphase2/commit/61ea8e4e9aa3d5752402c3fd8d783f7c97a659e5#r142406075

Dort ist ein Localer Pfad angegeben. Es könnte sein, dass nicht alles so funktioniert, wie es sollte.

**Comment by frndotmsn** [comment]
./gradlew cleanEclipse und ./gradlew eclipse sollten das problem lösen, es dürfen aber keine lokalen .classpath dateien comitted werden (ggf. in .gitignore?)

**Comment by Mcrtin** [comment]
sie ist tatsächlich in der .gitignore drin, wird aber trotzdem committet
